---
title: "PSC205A Assignment 01: Matrix Algebra"
format: pdf
---

# Q1 Compute A + B

```{r}
A <- matrix(
  c(1,    4,   2,
    2,    0,  -5,
    -1,   2,   1,
    0,    1,    2
  ), nrow = 3, ncol=4)

B <- matrix(
  c(3, 1, 2,
    -4, 5, -1,
    1, 0, 3,
    2, 3, -1), nrow=3, ncol=4
)

A + B
```

$$
A + B = \begin{bmatrix}
1 & 2 & -1 & 0 \\
4 & 0 & 2 & 1 \\
2 & -5 & 1 & 2 \\
\end{bmatrix} + \begin{bmatrix}
3 & -4 & 1 & 2 \\
1 & 5 & 0 & 3 \\
2 & -1 & 3 & -1 \\
\end{bmatrix} = \begin{bmatrix}
4 & -2 & 0 & 2 \\
5 & 5 & 2 & 4 \\
4 & -6 & 4 & 1 \\
\end{bmatrix}
$$


# Q2 Find $H$ such that $A + B - H = 0$

```{r}
A <- matrix(
  c(1, 3, 5,
    2, 4, 6
  ), 3, 2, byrow=FALSE
)

B <- matrix(c(
  -3, 1, 4,
  -2, -5, 3
),3, 2, byrow=FALSE)

H <- A + B
H
```
$$

A + B - H = 0\\ 

\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6 \\
\end{bmatrix} + 
\begin{bmatrix}
-3 & -2 \\
1 & -5  \\
4 & 3 \\
\end{bmatrix} -
\begin{bmatrix}
p & q \\
r & s  \\
t & u \\
\end{bmatrix} = 0\\
\begin{bmatrix}
-2 & 0 \\
4 & -1  \\
9 & 9 \\
\end{bmatrix} -
\begin{bmatrix}
p & q \\
r & s  \\
t & u \\
\end{bmatrix}
= 0\\
\begin{bmatrix}
-2 & 0 \\
4 & -1  \\
9 & 9 \\
\end{bmatrix} -
\begin{bmatrix}
p & q \\
r & s  \\
t & u \\
\end{bmatrix} +
\begin{bmatrix}
p & q \\
r & s  \\
t & u \\
\end{bmatrix} =
0 + 
\begin{bmatrix}
p & q \\
r & s  \\
t & u \\
\end{bmatrix}\\
\begin{bmatrix}
p & q \\
r & s  \\
t & u \\
\end{bmatrix} = 
\begin{bmatrix}
-2 & 0 \\
4 & -1  \\
9 & 9 \\
\end{bmatrix}

$$

# Q3. Compute A * B

```{r}
A <- c(4, 5, 6)
B <- matrix(c(2, 3, -1), 3, 1)

A %*% B
```

$$

\begin{vmatrix}
4 \\ 5 \\ 6
\end{bmatrix}
\begin{bmatrix}
2\\3\\-1
\end{bmatrix} =
[17]
$$
# Q4. Compute A * B

```{r}
A <- matrix(c(
  2, 1,
  3, 5,
  4, 6
), 2, 3)
B <- matrix(c(1, 2, 3), 3, 1)

A %*% B
```

# Q5. Compute $A * B$

```{r}
A <- matrix(c(
  1, 1, 1,
  2, 3, 2,
  3, 3, 4
), 3, 3)

B <- matrix(c(
  6, -1, 1,
  -2, 1, 0,
  -3, 0, 1
), 3, 3)

A %*% B
```

# Q6. Compute $A^3$

```{r}
A <- matrix(c(
  2, -1, 1,
  -2, 3, 2,
  -4, 4, -3
), 3, 3)

A %*% A %*% A
```

# Q7. Compute $A^3$

```{r}
A <- matrix(c(
  1, 5, -2,
  1, 2, -1,
  3, 6, -3
), 3, 3)

A %*% A %*% A
```

# Q8. Verify that $A = B^{-1}$ by computing $AB$ and $BA$ where:

$$
\begin{aligned}
A &= B^{-1} \\
AB &= B^{-1}B \\
AB &= I
\end{aligned}
$$

```{r}
A <- matrix(c(
  3, 1,
  -1, -2
), 2, 2)

B <- matrix(c(
  .4, .2,
  -.2, -.6
), 2, 2)

A %*% B
B %*% A
```

## Compute $A'$

```{r}
A <- matrix(c(
  1, 4, 2,
  2, 0 ,-5,
  -1, 2, 1,
  0, 1, 2
), 3, 4)

t(A)
```
## Compute $tr(A)$

$$
tr(A)=\sum_{i=1}^n a_{ii}
$$

```{r}
A <- matrix(c(
  1, 3,
  2, 4
), 2, 2) 

sum(diag(A))
```
## Compute $|A|$

$$
\begin{aligned}
|A| &= (a * d) - (b * c)\\
|A| &= (1*4) - (2 * 3)\\
|A| &= 4-6\\
|A| &=-2
\end{aligned}
$$


```{r}
A <- matrix(c(
  1, 3,
  2, 4
), 2, 2)
det(A)
```


