% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={PSC 204B Homework 1},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{PSC 204B Homework 1}
\author{}
\date{\vspace{-2.5em}Due Date: January 19, 2024}

\begin{document}
\maketitle

\hypertarget{question-1-2-points}{%
\section{\texorpdfstring{Question 1 \textbf{(2
points)}}{Question 1 (2 points)}}\label{question-1-2-points}}

Fit a simple linear regression model using biological sex (\emph{sex}; 0
= male; 1 = female) to predict depression (\emph{CESD}). Write out the
predicted regression equation using R markdown equation notation in the
space below (see the lab), and interpret each parameter (see the lab for
what is expected). Round all numbers to two decimal places.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Code}
\NormalTok{mod1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(CESD }\SpecialCharTok{\textasciitilde{}}\NormalTok{ sex, }\AttributeTok{data =}\NormalTok{ hw1)}
\FunctionTok{summary}\NormalTok{(mod1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = CESD ~ sex, data = hw1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -12.236  -3.236  -1.236   2.209  35.764 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   9.7910     0.1910   51.25   <2e-16 ***
## sex           2.4451     0.2262   10.81   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 6.433 on 3948 degrees of freedom
## Multiple R-squared:  0.02873,    Adjusted R-squared:  0.02849 
## F-statistic: 116.8 on 1 and 3948 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{itemize}
\tightlist
\item
  \textbf{Equation}:
  \(\widehat{Depression_i} = 9.79 + 2.45 \times Sex_i\)
\item
  \textbf{(Intercept)}: The expected value of depression is 9.79 when
  sex is male.
\item
  \textbf{Sex}: Females are predicted to have 2.45 more units of
  depression than males. This slope is significantly different from 0,
  indicating that Depression and sex are significantly associated.
\end{itemize}

\hypertarget{question-2-6.5-points}{%
\section{\texorpdfstring{Question 2 \textbf{(6.5
points)}}{Question 2 (6.5 points)}}\label{question-2-6.5-points}}

\hypertarget{part-a-2.5-points}{%
\subsection{\texorpdfstring{Part a) \textbf{(2.5
points)}}{Part a) (2.5 points)}}\label{part-a-2.5-points}}

Fit a simple linear regression model using neuroticism (\emph{N}) to
predict stress (\emph{Stress}). Write out the predicted regression
equation and interpret each of the parameters found in the regression
model.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Code}
\NormalTok{mod2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Stress }\SpecialCharTok{\textasciitilde{}}\NormalTok{ N, }\AttributeTok{data =}\NormalTok{ hw1)}
\FunctionTok{summary}\NormalTok{(mod2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Stress ~ N, data = hw1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.333  -4.139  -1.027   2.943  26.207 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -2.26540    0.57417  -3.945  8.1e-05 ***
## N            0.35698    0.01026  34.791  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.97 on 3948 degrees of freedom
## Multiple R-squared:  0.2346, Adjusted R-squared:  0.2345 
## F-statistic:  1210 on 1 and 3948 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{itemize}
\item
  \textbf{Equation}:
  \(\widehat{Stress_i} = -2.66 + 0.36 \times Neuroticism_i\)
\item
  \textbf{(Intercept)}: The expected value of stress is -2.27 when
  Neuroticism is equal 0.
\item
  \textbf{N}: An one-unit increase in Neuroticism is associated with a
  0.36 increase in Stress. This slope is significantly different from 0,
  indicating that Stress and Neuroticism are significantly associated.
\end{itemize}

\hypertarget{part-b-1-point}{%
\subsection{\texorpdfstring{Part b) \textbf{(1
point)}}{Part b) (1 point)}}\label{part-b-1-point}}

Plot the model diagnostic plots, and assess whether the assumptions of
linearity, homogeneity of variances, and normality of residuals are met.
Explain your reasoning.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(mod2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Homework1_2024_files/figure-latex/unnamed-chunk-7-1.pdf}
\includegraphics{Homework1_2024_files/figure-latex/unnamed-chunk-7-2.pdf}
\includegraphics{Homework1_2024_files/figure-latex/unnamed-chunk-7-3.pdf}
\includegraphics{Homework1_2024_files/figure-latex/unnamed-chunk-7-4.pdf}

\begin{itemize}
\item
  \textbf{Linearity}: The predicted line of Residuals vs Fitted values
  is expected to be flat to indicate zero correlation between the
  predicted and residual values. The assumption of linearity in this
  model appears to be meeting the assumption of linearity well.
\item
  \textbf{Homogeneity of Variances}:
\item
  \textbf{Normality of Residuals}: The normality of residuals can be
  assessed with the QQ Plot. All of the points are expected to fall on
  the diagonal line. In this model, we observe an expressive departure
  from normality for the residuals since the standardized residuals
  greater than zero show a positive slope, deviating from the dotted
  reference line.
\end{itemize}

\hypertarget{part-c-2.5-points}{%
\subsection{\texorpdfstring{Part c) \textbf{(2.5
points)}}{Part c) (2.5 points)}}\label{part-c-2.5-points}}

Repeat the regression analysis above in Part a, but using mean-centered
Neuroticism (\emph{N}) to predict \emph{Stress}. Call the mean-centered
Neuroticism variable \emph{N\_c}. Write out the predicted regression
equation and interpret each of the parameters found in the regression
model. \textbf{In each of your interpretations, comment on whether the
parameter changed from the original analysis, and why or why not.}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Code}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\item
  \textbf{Equation}: \(\widehat{Stress_i} = WRITE.EQUATION.HERE\)
\item
  \textbf{(Intercept)}: WRITE ANSWER HERE
\item
  \textbf{N}: WRITE ANSWER HERE
\end{itemize}

\hypertarget{part-d-0.5-points}{%
\subsection{\texorpdfstring{Part d) \textbf{(0.5
points)}}{Part d) (0.5 points)}}\label{part-d-0.5-points}}

Using the model from part (b), what is the predicted score for someone
who scores 1.5 points \emph{above the mean}?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Code}
\end{Highlighting}
\end{Shaded}

\hypertarget{question-3-1.5-points}{%
\section{\texorpdfstring{Question 3 \textbf{(1.5
points)}}{Question 3 (1.5 points)}}\label{question-3-1.5-points}}

Create two scatter plots to illustrate the relation between Stress and
Neuroticism in the two analyses performed in Question 2. Arrange the
graphs in two rows. Stress should be on the y axis in both graphs. In
the first row, show the relationship between Stress and uncentered
Neuroticism (\emph{N}). In the second row, show the relationship between
Stress and mean-centered Neuroticism (\emph{N\_c}). On each graph, add a
line of best. Be sure to label your axes, and make sure that all graphs
have the same x-axis and y-axis range.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Code}
\end{Highlighting}
\end{Shaded}

\hypertarget{extra-credit-1-point}{%
\section{\texorpdfstring{Extra Credit \textbf{(1
point)}}{Extra Credit (1 point)}}\label{extra-credit-1-point}}

Conduct a regression to assess whether min-centered Neuroticism
(\emph{N\_min}) predicts \textbf{median-centered} \emph{Stress}
(\emph{Stress\_med}). In the space below, report and interpret the
intercept. Keep in mind that the value of the intercept is now relative
to something since it has been centered.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Code}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\item
  \textbf{Report the value of the intercept}: WRITE ANSWER HERE
\item
  \textbf{Interpret the intercept}: WRITE ANSWER HERE
\end{itemize}

\end{document}
