---
title: "Cross-cultural adaptation of the Dysfunctional Beliefs and Attitudes about Sleep scale"
subtitle: "PSC205 Applied Multivariate Statistics"
author: "Marwin Carmo"
format: 
  revealjs:
    scrollable: true
    incremental: true
    code-tools: true
    code-copy: true
    code-line-numbers: true
    code-link: true
    preview-links: true
    slide-number: true
    self-contained: true
    fig-height: 4
    fig-width: 6
    fig-align: center
    margin-left: "0"
    margin-right: "0"
    width: 1400
    callout-icon: false
    # height: 900
    footer: "PSC205 Applied Multivariate Statistics"
    logo: "https://github.com/emoriebeck/psc290-data-viz-2022/raw/main/01-week1-intro/02-code/02-images/ucdavis_logo_blue.png"
editor: source
execute:
  echo: true
editor_options: 
  chunk_output_type: console
---

## Background

- The Dysfunctional Beliefs and Attitudes About Sleep Scale is a widely used tool in clinical and research settings to examine sleep-related thoughts.

- It is composed of 16 items, conformed into a 4-factor structure: (a) consequences of insomnia, (b) worry about sleep, (c) sleep expectations, (d) medication, and a fifth second-order general factor.

- There have been discrepancies among studies regarding the DBAS items and factors' accuracy in representing the underlying construct, indicating a need for additional psychometric research on this measurement tool.

## Objectives

- This study aimed to create a Brazilian-Portuguese adaptation of the Dysfunctional Beliefs and Attitudes about Sleep Scale (DBAS-16), analyzing its factorial structure, reliability, and construct validity. 

## Methods

### Participants

- Participants with and without insomnia were recruited from March 2021 to July 2022 through social media.

- The final sample consisted of 1385 participants, of which 80.78% were female, and 73.51% reported insomnia symptoms. The mean age was 38.39 years (SD = 9.79, range: 18--59). 

## Methods

### Instruments

- Dysfunctional Beliefs and Attitudes About Sleep

- Insomnia Severity Index

- The Hospital Anxiety and Depression Scale

## Methods

### Statistical analyses

- 1st stage:
  - Confirmatory Factor Analyses (CFA) as a first test for structural validity.
  - Analyses of measurement invariance across insomnia severity status (good and bad sleepers) and across two administrations 14-days apart.
  - McDonald's omega hierarchical ($\omega_h$) to estimate internal consistency.
  - Convergent validity was assessed by estimating a structural equation model where the DBAS-16 factors, insomnia severity, and the HADS subscales of depression and anxiety were allowed to correlate.

## Methods

### Statistical analyses

- 2nd stage:
  - Given the poor CFA results, the sample was divided into two equal parts for the new stages of derivation and confirmation.
  - The derivation step aimed to obtain an optimal network structure using the Exploratory Graph Analysis (EGA) framework.
  - The confirmation phase was used to test if the new structure was replicated and test its plausibility against the theoretical model using CFA.
  
## Results so far

- The four-factor structure had acceptable indices by traditional and dynamic fit indices: $\chi^2$ (98, N = 1385) = 974.41, RMSEA = .094 90% CI [.089, .100], CFI = .891, SRMR = .074.

- The DBAS-16's original structure was noninvariant across good and bad sleepers.

- The model structure and factor loadings remained consistent over the two timepoints.

- Except for "expectations," DBAS-16 factors had positive moderate-to-strong correlations with insomnia severity, anxiety and depression.

- EGA revealed that two dimensions better reflect this sample's underlying structure of dysfunctional beliefs and attitudes toward sleep.