---
title: "HW2: Community Detection"
author: "Your Name Here"
format: pdf
editor: visual
---

# Introduction

Welcome to Homework Assignment No. 2. For this week's assignment, you'll need to visit [the course website](https://jonathanpark.dev/NetworkAnalysis/hwapp.html). There, you'll find a shiny app to generate the graph you'll need for your homework assignment.

## Instructions

-   Input your first and last name
-   Input the due date of the assignment \[May 4, 2025\]
-   Download the `.RDS` file which contains your graph
-   Load that `.RDS` file into your `R` environment and begin the assignment
    -   This can be done with the command, \`readRDS()\`\`

> Note: you may review the answers to graphs from any other **past** date. So, if you'd like to check if your code is correct, feel free to do so; however, you may not view the answers for any future dates. **Be sure to submit the graph/answers for the due date above!**

Below, you will find a template of the questions and fields to provide answers in either `R` or text format. Please use a mix of code and text to answer each question.

## Questions

### **Question 1**. Save the adjacency matrix of your graph object. Refer to W1 for the code. Print the first 3 rows of your matrix using head().

#### Answer

### **Question 2**. Apply k-means clustering to your adjacency matrix using a range of $k$-values and save the results. Print the "withinss" for the first three items in the list (hint: use --\> results\[\[i\]\]\[\["withinss"\]\], where i = item index). As k increases, does the within-cluster variation for each cluster increase or decrease?

#### Answer

### **Question 3**. Plot the withinss values for all list items in your k-means clustering results. Based on the plot, what is the most optimal value of 'k' (i.e., number of clusters in your network)?

#### Answer

### **Question 4**. What is Q for the above finding (hint: you will need use results\[\[k\]\]\[\["cluster"\]\] in the membership argument of modularity())?

#### Answer

### *Question 5*. Apply fuzzy c-means clustering to your adjacency matrix using a range of $k$-values and save the results. Using the optimal value of k from Q3, print the first 10 rows for the cluster confidence matrix (u). Which node is most likely to be in Cluster k-1?

#### Answer

### *Question 6*. Apply the Walktrap algorithm to your graph, with t = 4 (default value). Plot the resulting graph and highlight the groups identified in your Walktrap results.

#### Answer

### *Question 7*. Apply spectral clustering to your graph. You will need both your adjacency matrix and graph object to derive your Laplacian matrix. Use the same value of $k$ as in previous questions. Calculate and report modularity, $Q$ for your results.

#### Answer

### *Question 8*. Calculate and compare $Q$ (modularity) for each set of results (k-means, c-means, WalkTrap, spectral). Which approach resulted in the highest $Q$?

#### Answer